DROP TABLE IF EXISTS class;
CREATE TABLE class (
  id         INT AUTO_INCREMENT NOT NULL,
  className  VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS post;
CREATE TABLE post (
  postID    INT AUTO_INCREMENT NOT NULL,
  classID   INT,
  FOREIGN KEY (classID) REFERENCES class(id),
  postName  VARCHAR(128) NOT NULL,
  postContent VARCHAR(128) NOT NULL,
  PRIMARY KEY (`postID`)
);

INSERT INTO class
  (className)
VALUES
  ('COP5000')