DROP TABLE IF EXISTS class;
CREATE TABLE class (
  id         INT AUTO_INCREMENT NOT NULL,
  className  VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO class
  (className)
VALUES
  ('CEN3031');